[phases.setup]
nixPkgs = ['nodejs_20', 'openssl']

[phases.build]
cmds = [
  'cd backend',
  'npm install',
  'npx prisma generate',
  'npm run build'
]

[start]
cmd = 'cd backend && npm run start:migrate'
