[phases.setup]
nixPkgs = ['nodejs_20', 'openssl']

[phases.build]
cmds = [
  'cd backend',
  'npm install',
  'npx prisma generate',
  'npm run build',
  'chmod +x start.sh'
]

[start]
cmd = 'cd backend && ./start.sh'
