[phases.setup]
nixPkgs = ['nodejs_20', 'openssl']

[phases.build]
cmds = [
  'cd backend',
  'npm install',
  'npx prisma generate',
  'npm run build'
]

[phases.deploy]
cmds = ['cd backend && npm start']

[start]
cmd = 'cd backend && npm start'
